import type { Vehicle } from '@/types'

export const mockVehicles: Vehicle[] = [
  {
    id: 'vehicle-001',
    make: 'BMW',
    model: 'E90 320d',
    year: 2007,
    engine: 'N47D20',
    fuel: 'Diesel',
    vin: 'WBAPH1C56BE123456',
  },
  {
    id: 'vehicle-002',
    make: 'Mercedes-Benz',
    model: 'C220 CDI W204',
    year: 2010,
    engine: 'OM651',
    fuel: 'Diesel',
  },
  {
    id: 'vehicle-003',
    make: 'VW',
    model: 'Golf 5 1.9 TDI',
    year: 2005,
    engine: 'BKC',
    fuel: 'Diesel',
  },
  {
    id: 'vehicle-004',
    make: 'Toyota',
    model: 'Yaris 1.0',
    year: 2016,
    engine: '1KR-FE',
    fuel: 'Βενζίνη',
  },
  {
    id: 'vehicle-005',
    make: 'Opel',
    model: 'Astra H 1.6',
    year: 2006,
    engine: 'Z16XER',
    fuel: 'Βενζίνη',
  },
  {
    id: 'vehicle-006',
    make: 'Audi',
    model: 'A3 2.0 TDI 8P',
    year: 2008,
    engine: 'BKD',
    fuel: 'Diesel',
  },
  {
    id: 'vehicle-007',
    make: 'Peugeot',
    model: '208 1.2 PureTech',
    year: 2015,
    engine: 'HMZ',
    fuel: 'Βενζίνη',
  },
  {
    id: 'vehicle-008',
    make: 'Ford',
    model: 'Focus 1.6 TDCi',
    year: 2009,
    engine: 'HHDA',
    fuel: 'Diesel',
  },
]
